Repository E3SM-Project/zppy, pull requests merged in 2021-06, with the labels that each got.

#63 Add MPAS-Analysis parameters for mapping in parallel
  zppy/templates/default.ini
  zppy/templates/mpas_analysis.bash
Labels: new feature

#68 Simplify the MPAS-Analysis config file
  zppy/templates/mpas_analysis.bash
Labels: nice to have

#64 Include MPAS-Analysis ncclimo options in zppy config
  zppy/templates/default.ini
  zppy/templates/mpas_analysis.bash
Labels: nice to have

#65 Update the default parallelTaskCount in MPAS-Analysis
  zppy/templates/default.ini
Labels: nice to have

#69 Release v1.0.0rc2
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version

#73 Add `cfg` to `setup.py`
  setup.py
Labels: bug

#74 Fixes for rc3
  zppy/templates/coupled_global.py
  zppy/templates/default.ini
  zppy/templates/mpas_analysis.bash
Labels: bug

#79 Release v1.0.0rc3
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version

#83 Automate docs
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  .gitignore
  conda/dev.yml
  docs/Makefile
  docs/source/_static/style.css
  docs/source/_templates/layout.html
  docs/source/_templates/versions.html
  docs/source/conf.py
  docs/source/contributing.rst
  docs/source/figures/README
  docs/source/figures/zppy_schematic.pdf
  docs/source/figures/zppy_schematic.pptx
  docs/source/figures/zppy_schematic.svg
  docs/source/getting_started.rst
  docs/source/index.rst
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  docs/source/post.rrm_simulation.cfg
  docs/source/tutorial.rst
Labels: DevOps, documentation

#86 Add QA tools
  .github/workflows/build_workflow.yml
  .pre-commit-config.yaml
  .vscode/settings.json
  NOTICE
  README.md
  conda/dev.yml
  docs/source/_static/pre-commit-passing.png
  docs/source/conf.py
  docs/source/dev_guide/git-flow.svg
  docs/source/dev_guide/index.rst
  docs/source/dev_guide/pre-commit-flow.svg
  docs/source/dev_guide/project-standards.rst
  docs/source/dev_guide/release.rst
  docs/source/getting_started.rst
  docs/source/index.rst
  pyproject.toml
  setup.cfg
  setup.py
  tests/integration/test_bash_generation.py
  tests/integration/test_complete_run.py
  tests/integration/test_environment_commands.py
  tests/test_sections.cfg
  tests/test_sections.py
  tests/test_subsections.cfg
  zppy/__init__.py
  zppy/__main__.py
  zppy/amwg.py
  zppy/climo.py
  zppy/e3sm_diags.py
  zppy/e3sm_diags_vs_model.py
  zppy/global_time_series.py
  zppy/mpas_analysis.py
  zppy/templates/amwg.csh
  zppy/templates/climo.bash
  zppy/templates/coupled_global.py
  zppy/templates/e3sm_diags.bash
  zppy/templates/e3sm_diags/lat_lon_conus.cfg
  zppy/templates/e3sm_diags_vs_model.bash
  zppy/templates/ocean_month.py
  zppy/templates/readTS.py
  zppy/templates/slurm_header.sh
  zppy/templates/ts.bash
  zppy/ts.py
  zppy/utils.py
Labels: DevOps
