Repository E3SM-Project/zppy, pull requests merged in 2021-05, with the labels that each got.

#37 Automate global time series plots
  global_time_series.py
  global_time_series/generate_global_time_series_plots.sh
  post.py
  templates/coupled_global.py
  templates/default.ini
  templates/global_time_series.bash
  templates/ocean_month.py
  templates/readTS.py
Labels: for next version, new feature

#34 Add diurnal cycle diagnostics
  e3sm_diags.py
  templates/climo.bash
  templates/default.ini
  templates/e3sm_diags.bash
Labels: for next version, new feature

#45 Add tests
  .gitignore
  README.md
  conda/dev.yml
  tests/test_bash_generation.cfg
  tests/test_bash_generation.py
  tests/test_complete_run.cfg
  tests/test_complete_run.py
  tests/test_sections.py
  tests/test_subsections.py
  zppy/amwg.py
  zppy/climo.py
  zppy/e3sm_diags.py
  zppy/e3sm_diags_vs_model.py
  zppy/global_time_series.py
  zppy/mpas_analysis.py
  zppy/templates/default.ini
  zppy/templates/global_time_series.bash
  zppy/templates/ocean_month.py
  zppy/ts.py
Labels: for next version, testing

#52 Add GitHub Actions release workflow
  .github/workflows/release_workflow.yml
  README.md
Labels: DevOps

#49 Test environment_commands
  tests/integration/test_environment_commands.cfg
  tests/integration/test_environment_commands.py
Labels: for next version, testing

#55 Add conda channel label assignment in release workflow
  .github/workflows/release_workflow.yml
Labels: DevOps

#56 Add conda channel label assignment in release workflow
  .github/workflows/release_workflow.yml
Labels: DevOps

#58 Update source section of meta.yaml
  conda/meta.yaml
Labels: DevOps

#59 Release v1.0.0rc1
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version
