Repository E3SM-Project/zppy, pull requests merged in 2021-08, with the labels that each got.

#91 Add tbump to simplify version bumping
  conda/dev.yml
  docs/source/dev_guide/release.rst
  tbump.toml
Labels: DevOps, for next version

#112 Update E3SM Diags testing
  .gitignore
  docs/source/dev_guide/testing.rst
  tests/integration/test_bash_generation.cfg
  tests/integration/test_bash_generation.py
  tests/integration/test_complete_run.cfg
  tests/integration/test_complete_run.py
  tests/integration/test_environment_commands.cfg
  tests/integration/test_environment_commands.py
Labels: testing

#113 Enable revisions to old docs
  .github/workflows/build_workflow.yml
  .github/workflows/release_workflow.yml
  docs/source/conf.py
Labels: DevOps

#114 Explain environment_commands
  _build/html/v1.0.0/getting_started.html
  _build/html/v1.0.0/parameters.html
  _build/html/v1.0.0/tutorial.html
Labels: documentation

#118 Update E3SM Unified paths
  zppy/__main__.py
Labels: for next version

#119 Update docs
  docs/source/figures/README
  docs/source/figures/zppy_dependencies.png
  docs/source/figures/zppy_jobs.png
  docs/source/figures/zppy_schematic.pdf
  docs/source/figures/zppy_schematic.pptx
  docs/source/figures/zppy_schematic.svg
  docs/source/index.rst
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  docs/source/schematics.rst
Labels: documentation, for next version

#124 Add extra_vars option for in the "ts" section
  tests/test_sections.py
  zppy/templates/default.ini
  zppy/templates/ts.bash
Labels: new feature
