Repository E3SM-Project/zppy, pull requests merged in 2021-07, with the labels that each got.

#90 Improve docs
  docs/source/dev_guide/index.rst
  docs/source/dev_guide/testing.rst
  docs/source/post.mysimulation.cfg
  docs/source/tutorial.rst
  tests/integration/test_complete_run.py
Labels: documentation

#95 Disable MPI in cdms2 before calling cdscan
  zppy/templates/e3sm_diags.bash
  zppy/templates/global_time_series.bash
Labels: bug

#81 Fixes for rc4
  .gitignore
  setup.py
  tests/integration/test_complete_run.py
  tests/integration/test_environment_commands.py
  zppy/amwg.py
  zppy/climo.py
  zppy/e3sm_diags.py
  zppy/e3sm_diags_vs_model.py
  zppy/global_time_series.py
  zppy/mpas_analysis.py
  zppy/templates/climo.bash
  zppy/templates/default.ini
  zppy/templates/e3sm_diags.bash
  zppy/templates/e3sm_diags_vs_model.bash
  zppy/templates/global_time_series.bash
  zppy/templates/mpas_analysis.bash
  zppy/templates/ts.bash
  zppy/ts.py
Labels: bug

#89 Release v1.0.0rc4
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version

#97 Shorten arguments for ncclimo
  zppy/templates/climo.bash
  zppy/templates/ts.bash
Labels: bug

#103 Release v1.0.0rc5
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version

#105 Modify `ts_num_years`
  zppy/templates/coupled_global.py
  zppy/templates/global_time_series.bash
  zppy/templates/ocean_month.py
Labels: bug

#107 Release v1.0.0
  conda/meta.yaml
  setup.py
  zppy/__init__.py
Labels: update version

#84 Docs for testing E3SM Unified
  docs/source/dev_guide/index.rst
  docs/source/dev_guide/testing_e3sm_unified.cfg
  docs/source/dev_guide/testing_e3sm_unified.rst
  docs/source/index.rst
Labels: documentation

#106 Refactor coupled_global
  .pre-commit-config.yaml
  pyproject.toml
  zppy/templates/coupled_global.py
  zppy/templates/global_time_series.bash
Labels: nice to have
