Repository E3SM-Project/zppy, pull requests merged in 2021-09, with the labels that each got.

#126 Add streamflow diags
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  docs/source/tutorial.rst
  tests/integration/test_bash_generation.cfg
  tests/integration/test_complete_run.cfg
  tests/integration/test_environment_commands.cfg
  zppy/e3sm_diags.py
  zppy/templates/default.ini
  zppy/templates/e3sm_diags.bash
  zppy/templates/e3sm_diags_vs_model.bash
Labels: new feature, for next version

#130 Use debug queue for integration tests
  tests/integration/test_complete_run.cfg
  tests/integration/test_environment_commands.cfg
Labels: nice to have, testing

#138 Add campaign parameter
  .gitignore
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  docs/source/post.rrm_simulation.cfg
  docs/source/tutorial.rst
  tests/test_sections.py
  zppy/__main__.py
  zppy/templates/default.ini
  zppy/templates/water_cycle.cfg
Labels: new feature, for next version

#136 Add high resolution support
  zppy/templates/climo.bash
  zppy/templates/ts.bash
Labels: new feature, for next version

#137 Print settings
  zppy/amwg.py
  zppy/climo.py
  zppy/e3sm_diags.py
  zppy/e3sm_diags_vs_model.py
  zppy/global_time_series.py
  zppy/mpas_analysis.py
  zppy/ts.py
Labels: new feature, for next version

#139 Bump to 1.1.0rc1
  conda/meta.yaml
  setup.py
  tbump.toml
  zppy/__init__.py
Labels: for next version, update version
