Repository E3SM-Project/zppy, pull requests merged in 2022-01, with the labels that each got.

#173 Remove `e3sm_unified` option
  docs/source/dev_guide/testing_e3sm_unified.cfg
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  docs/source/post.rrm_simulation.cfg
  tests/integration/test_bash_generation.cfg
  tests/integration/test_campaign_cryosphere.cfg
  tests/integration/test_campaign_cryosphere_override.cfg
  tests/integration/test_campaign_none.cfg
  tests/integration/test_campaign_water_cycle.cfg
  tests/integration/test_campaign_water_cycle_override.cfg
  tests/integration/test_complete_run.cfg
  tests/integration/test_environment_commands.cfg
  tests/test_sections.py
  zppy/__main__.py
  zppy/templates/default.ini
Labels: for next version, Incompatible API change

#171 Remove `srun` command from `mpas_analysis` command
  zppy/templates/mpas_analysis.bash
Labels: for next version

#174 Fix E3SM-Unified path for Cori-Haswell and -KNL
  zppy/__main__.py
Labels: bug, for next version

#176 Add a template for high-res E3SM v1 runs
  zppy/templates/high_res_v1.cfg
Labels: new feature, for next version

#169 Add tropical cyclone diags
  docs/source/dev_guide/new_diags_set.rst
  docs/source/dev_guide/new_task.rst
  docs/source/parameters.rst
  docs/source/post.mysimulation.cfg
  tests/integration/test_bash_generation.cfg
  tests/integration/test_campaign_cryosphere.cfg
  tests/integration/test_campaign_cryosphere_override.cfg
  tests/integration/test_campaign_none.cfg
  tests/integration/test_campaign_water_cycle.cfg
  tests/integration/test_campaign_water_cycle_override.cfg
  tests/integration/test_complete_run.cfg
  tests/integration/test_environment_commands.cfg
  zppy/__main__.py
  zppy/e3sm_diags.py
  zppy/tc_analysis.py
  zppy/templates/default.ini
  zppy/templates/e3sm_diags.bash
  zppy/templates/tc_analysis.bash
Labels: new feature

#179 Improve documentation and testing for campaigns
  docs/source/campaigns.rst
  docs/source/dev_guide/testing.rst
  docs/source/index.rst
  tests/integration/test_campaign.py
  tests/integration/test_campaign_high_res_v1.cfg
  tests/integration/update_campaign_expected_files.sh
Labels: documentation, testing

#182 Bump to 2.0.0rc1
  conda/meta.yaml
  setup.py
  tbump.toml
  zppy/__init__.py
Labels: update version

#185 Bump to 2.0.0rc2
  conda/meta.yaml
  setup.py
  tbump.toml
  zppy/__init__.py
Labels: update version
